// SPDX-License-Identifier: Apache-2.0

// Command licensesnap prints the NOTICE file: ACOR's own attribution followed by
// the copyright notice and verbatim license text of every third-party module
// linked into the acor binary.
//
// The output is committed as NOTICE, which is what makes the attribution an
// artifact CI can diff. The MIT and BSD licenses ACOR's dependencies carry all
// require that their copyright notice and full license text be reproduced in
// binary redistributions, so the generated file is shipped inside the release
// archives and the container images, not just kept in the repository.
//
// Scope is ./cmd/acor, the only binary this project distributes. The server/
// module is a source-only library: a consumer runs `go get` and the go command
// fetches its dependencies from the proxy with their own LICENSE and NOTICE
// files intact, so this project never redistributes them and owes no notice for
// them. benchmarks/ never leaves the repository.
//
// License texts are copied byte-for-byte rather than summarized, because
// reproducing the text is the obligation. PATENTS and NOTICE files are copied
// too when a module has them: golang.org/x/sync carries an additional patent
// grant that has to travel with it.
//
// SPDX identifiers come from licenseIDs below and are never inferred from the
// license text. A wrong identifier in this file is a wrong legal claim, and
// distinguishing MIT from BSD-2-Clause from ISC by pattern matching is exactly
// where inference gets it wrong. An unmapped module is a hard error, so adding a
// dependency fails the build until someone reads its license and records it.
//
// Usage: go run ./tools/licensesnap   (from the repository root)
package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const (
	target     = "./cmd/acor"
	selfModule = "github.com/skyoo2003/acor"
	regenerate = "make license-check"

	// moduleFields is the number of tab-separated fields the go list format below
	// emits per module: path, version, cache directory.
	moduleFields = 3
	ruleWidth    = 80

	header = `ACOR - Aho-Corasick automaton working On Redis
Copyright 2016-2026 Sungkyu Yoo

Licensed under the Apache License, Version 2.0 (see LICENSE).
`

	preamble = `The compiled ` + "`acor`" + ` binary bundles the third-party software listed below.
Each component remains under its own license, reproduced here in full.
`
)

// licenseIDs maps a module path to its SPDX identifier, read by hand from that
// module's license file. Deliberately not inferred — see the package doc.
var licenseIDs = map[string]string{
	"github.com/cespare/xxhash/v2": "MIT",
	"github.com/redis/go-redis/v9": "BSD-2-Clause",
	"go.uber.org/atomic":           "MIT",
	"golang.org/x/sync":            "BSD-3-Clause",
}

// licenseNames are the filenames a module may use for its license, in the order
// they are tried. Upstream is inconsistent: go-redis and x/sync use LICENSE,
// xxhash and go.uber.org/atomic use LICENSE.txt.
var licenseNames = []string{"LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING"}

// extraNames are additional files that carry terms and so must be reproduced
// alongside the license. x/sync's PATENTS is an additional IP grant; a NOTICE
// belonging to a dependency has to be propagated verbatim under Apache-2.0 4(d).
// No current dependency ships a non-empty NOTICE, but a future one will.
var extraNames = []string{"PATENTS", "NOTICE"}

type module struct {
	path    string
	version string
	dir     string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "licensesnap:", err)
		os.Exit(1)
	}
}

func run() error {
	mods, err := modules()
	if err != nil {
		return err
	}
	if len(mods) == 0 {
		// Never a legitimate result: the binary links go-redis at minimum. An
		// empty list means `go list` reported nothing useful, and silently
		// writing a NOTICE with no third-party section would drop every
		// attribution at once.
		return fmt.Errorf("no third-party modules found for %s", target)
	}

	out := &strings.Builder{}
	out.WriteString(header)
	fmt.Fprintf(out, "\n# Generated by tools/licensesnap. Regenerate with: %s\n", regenerate)
	fmt.Fprintf(out, "\n%s\nTHIRD-PARTY SOFTWARE\n%s\n\n%s", rule('='), rule('='), preamble)

	for _, m := range mods {
		id, ok := licenseIDs[m.path]
		if !ok {
			return fmt.Errorf("unknown license for %s; read its license file and add it to licenseIDs in tools/licensesnap/main.go", m.path)
		}

		text, name, err := licenseText(m)
		if err != nil {
			return err
		}

		fmt.Fprintf(out, "\n%s\n%s %s\nSPDX-License-Identifier: %s\n%s\n\n", rule('-'), m.path, m.version, id, rule('-'))
		out.WriteString(indent(text))

		for _, extra := range extraNames {
			// A dependency's own NOTICE must not be confused with its license
			// file; skip the case where the two are the same file.
			if extra == name {
				continue
			}
			// Path comes from `go list`, not from user input.
			b, err := os.ReadFile(filepath.Join(m.dir, extra)) //nolint:gosec
			// Absent is the common case, and an empty NOTICE is what
			// google.golang.org/grpc ships — neither is worth a heading.
			if err != nil || strings.TrimSpace(string(b)) == "" {
				continue
			}
			fmt.Fprintf(out, "\n%s (%s):\n\n", extra, m.path)
			out.WriteString(indent(string(b)))
		}
	}

	fmt.Print(out.String())
	return nil
}

// modules returns the third-party modules linked into the target binary, sorted
// by path and deduplicated. `go list -deps` walks the import graph of the built
// package, so it reports what actually ends up in the binary rather than what
// go.mod requires: go.uber.org/atomic is an indirect requirement that does get
// linked (through go-redis internals), while miniredis and gopher-lua are direct
// requirements that do not, being test-only.
func modules() ([]module, error) {
	const format = `{{if and .Module (not .Standard)}}{{.Module.Path}}	{{.Module.Version}}	{{.Module.Dir}}{{end}}`

	cmd := exec.CommandContext(context.Background(), "go", "list", "-deps", "-f", format, target)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list -deps %s: %w", target, err)
	}

	seen := map[string]bool{}
	var mods []module
	for line := range strings.SplitSeq(string(out), "\n") {
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) != moduleFields {
			return nil, fmt.Errorf("unexpected go list output: %q", line)
		}
		m := module{path: fields[0], version: fields[1], dir: fields[2]}
		if m.path == selfModule || seen[m.path] {
			continue
		}
		// Empty for a module replaced by a local directory, and for one that is
		// not in the cache. Either way there is no license file to read, and
		// guessing is not an option.
		if m.dir == "" {
			return nil, fmt.Errorf("no module cache directory for %s; run `go mod download`", m.path)
		}
		seen[m.path] = true
		mods = append(mods, m)
	}

	sort.Slice(mods, func(i, j int) bool { return mods[i].path < mods[j].path })
	return mods, nil
}

// licenseText returns a module's license text and the filename it came from.
func licenseText(m module) (text, filename string, err error) {
	for _, name := range licenseNames {
		// Path comes from `go list`, not from user input.
		b, readErr := os.ReadFile(filepath.Join(m.dir, name)) //nolint:gosec
		if readErr == nil {
			return string(b), name, nil
		}
	}
	return "", "", fmt.Errorf("no license file in %s for %s (tried %s)", m.dir, m.path, strings.Join(licenseNames, ", "))
}

// indent offsets a verbatim license text by four spaces so it is unambiguous
// where an upstream text starts and stops. Blank lines stay empty rather than
// becoming trailing whitespace, which the trailing-whitespace and
// end-of-file-fixer hooks would otherwise rewrite on commit and break the gate.
func indent(s string) string {
	var b strings.Builder
	for line := range strings.SplitSeq(strings.TrimRight(s, "\n"), "\n") {
		if line = strings.TrimRight(line, " \t"); line == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("    " + line + "\n")
	}
	return b.String()
}

func rule(c byte) string { return strings.Repeat(string(c), ruleWidth) }
