name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## What's Changed

  $CHANGES

categories:
  - title: "Breaking Changes"
    labels:
      - "breaking_changes"
  - title: "New Features"
    labels:
      - "feature_request"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Dependencies"
    labels:
      - "dependencies"
  - title: "Maintenance"
    labels:
      - "maintenance"
      - "github_actions"

version-resolver:
  minor:
    labels:
      - "breaking_changes"
      - "feature_request"
      - "enhancement"
  patch:
    labels:
      - "bug"
      - "documentation"
      - "dependencies"
      - "maintenance"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- No changes"
