changesDir: changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## [{{ .Version }}](https://github.com/skyoo2003/acor/releases/tag/{{ .Version }}) - {{ .Time.Format "2006-01-02" }}'
kindFormat: '### {{ .Kind }}'
changeFormat: '* {{ .Body }} ([#{{ .Custom.Issue }}](https://github.com/skyoo2003/acor/issues/{{ .Custom.Issue }}))'
kinds:
- Added
- Changed
- Deprecated
- Removed
- Fixed
- Security
custom:
- key: Issue
  label: Issue Number
  type: int
  minInt: 1