repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        args:
          - "--maxkb=10000"
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: detect-private-key
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
exclude: "helm/*"
