// SPDX-License-Identifier: Apache-2.0

// Command apisnap prints the exported surface of pkg/acor as sorted text, one
// symbol per line, so the v1 compatibility promise has an artifact CI can diff.
//
// The output is committed as api/v1.txt, which makes a public API change visible
// in the pull request that causes it: adding a symbol appends a line, removing
// one deletes a line. Nothing here prevents a removal — it only makes one
// impossible to do quietly, which is what "any bypass requires explicit recorded
// approval" means in practice.
//
// Struct fields and interface methods are included because the promise covers
// them specifically: structs ACOR returns may gain fields, and exported
// interfaces may not gain methods at all (docs/content/reference/compatibility.md).
// Type aliases print their right-hand side, so an alias reaching back into an
// internal package also shows up here.
//
// Doc comments and const values are deliberately absent. Documentation wording
// and error strings are explicitly not covered by the promise, so including them
// would fail the gate on every rewording.
//
// Usage: go run ./tools/apisnap   (from the repository root)
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	pkgDir     = "pkg/acor"
	pkgImport  = "github.com/skyoo2003/acor/pkg/acor"
	regenerate = "make api-check"
)

func main() {
	lines, err := snapshot(pkgDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "apisnap:", err)
		os.Exit(1)
	}

	out := &strings.Builder{}
	fmt.Fprintf(out, "# Public API surface of %s, frozen for the v1 line.\n", pkgImport)
	fmt.Fprintf(out, "# Generated by tools/apisnap. Regenerate with: %s\n", regenerate)
	fmt.Fprintf(out, "# A deleted line is a breaking change. See docs/content/reference/compatibility.md.\n")
	for _, l := range lines {
		fmt.Fprintln(out, l)
	}
	fmt.Print(out.String())
}

func snapshot(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	var lines []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		// parser.ParseDir would be shorter but returns the deprecated ast.Package,
		// and the surface spans files anyway — nothing here needs them grouped.
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		lines = append(lines, declLines(fset, f)...)
	}

	sort.Strings(lines)
	return dedupe(lines), nil
}

func declLines(fset *token.FileSet, f *ast.File) []string {
	var lines []string
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if l, ok := funcLine(fset, d); ok {
				lines = append(lines, l)
			}
		case *ast.GenDecl:
			lines = append(lines, genLines(fset, d)...)
		}
	}
	return lines
}

func funcLine(fset *token.FileSet, d *ast.FuncDecl) (string, bool) {
	if !d.Name.IsExported() {
		return "", false
	}
	sig := signature(fset, d.Type)
	if d.Recv == nil {
		return "func " + d.Name.Name + sig, true
	}
	// A method is only part of the surface if its receiver is too: a method on an
	// unexported type is unreachable from outside the package.
	recv := d.Recv.List[0].Type
	if !ast.IsExported(baseName(recv)) {
		return "", false
	}
	return fmt.Sprintf("method (%s) %s%s", render(fset, recv), d.Name.Name, sig), true
}

func genLines(fset *token.FileSet, d *ast.GenDecl) []string {
	var lines []string
	// Only the first spec of an iota group declares the type; the rest inherit it.
	// Recording the type per spec as written would make the snapshot depend on
	// declaration order — reordering a const block would move the annotation from
	// one line to another, and deleting the first constant would silently drop the
	// type from every constant under it.
	groupType := ""
	for _, spec := range d.Specs {
		switch s := spec.(type) {
		case *ast.ValueSpec:
			kind := "var"
			if d.Tok == token.CONST {
				kind = "const"
			}
			switch {
			case s.Type != nil:
				groupType = render(fset, s.Type)
			case len(s.Values) > 0:
				// Own value, so the type is inferred from it rather than inherited.
				groupType = ""
			}
			for _, n := range s.Names {
				if !n.IsExported() {
					continue
				}
				// The declared type only, never the value. Sentinel error identity
				// is promised; the message text explicitly is not.
				line := kind + " " + n.Name
				if groupType != "" {
					line += " " + groupType
				}
				lines = append(lines, line)
			}
		case *ast.TypeSpec:
			if !s.Name.IsExported() {
				continue
			}
			lines = append(lines, typeLines(fset, s)...)
		}
	}
	return lines
}

func typeLines(fset *token.FileSet, s *ast.TypeSpec) []string {
	name := s.Name.Name
	if s.Assign.IsValid() {
		// An alias is the same type as its right-hand side, so the RHS is part of
		// the surface. This is what catches a leak back into internal/.
		return []string{"type " + name + " = " + render(fset, s.Type)}
	}

	switch t := s.Type.(type) {
	case *ast.StructType:
		lines := []string{"type " + name + " struct"}
		for _, fld := range t.Fields.List {
			lines = append(lines, memberLines(fset, name, "field", fld)...)
		}
		return lines
	case *ast.InterfaceType:
		lines := []string{"type " + name + " interface"}
		for _, fld := range t.Methods.List {
			lines = append(lines, memberLines(fset, name, "method", fld)...)
		}
		return lines
	default:
		return []string{"type " + name + " " + render(fset, s.Type)}
	}
}

// memberLines renders one struct field or interface method. An embedded entry has
// no name of its own, so its type supplies one.
func memberLines(fset *token.FileSet, owner, kind string, fld *ast.Field) []string {
	if len(fld.Names) == 0 {
		embedded := baseName(fld.Type)
		if !ast.IsExported(embedded) {
			return nil
		}
		return []string{fmt.Sprintf("%s %s.%s %s", kind, owner, embedded, render(fset, fld.Type))}
	}

	var lines []string
	for _, n := range fld.Names {
		if !n.IsExported() {
			continue
		}
		if ft, ok := fld.Type.(*ast.FuncType); ok && kind == "method" {
			lines = append(lines, fmt.Sprintf("method %s.%s%s", owner, n.Name, signature(fset, ft)))
			continue
		}
		lines = append(lines, fmt.Sprintf("%s %s.%s %s", kind, owner, n.Name, render(fset, fld.Type)))
	}
	return lines
}

// signature renders a func type as the part that follows the name, so a printed
// "func(ctx context.Context) error" becomes "(ctx context.Context) error".
func signature(fset *token.FileSet, ft *ast.FuncType) string {
	return strings.TrimPrefix(render(fset, ft), "func")
}

// render prints an AST node on one line. Positions come from the original source,
// so go/printer reproduces its line breaks; collapsing whitespace is what keeps
// one symbol to one line regardless of how the declaration was formatted.
func render(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, node); err != nil {
		// Unreachable for a parsed node, and a panic here would be a worse
		// failure mode than a line that fails the diff loudly.
		return "<unprintable>"
	}
	return strings.Join(strings.Fields(buf.String()), " ")
}

// baseName reduces a type expression to the identifier a receiver or embedded
// field is named by: *T, T[K], and pkg.T all answer with their own last ident.
func baseName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return baseName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.IndexExpr:
		return baseName(t.X)
	case *ast.IndexListExpr:
		return baseName(t.X)
	}
	return ""
}

func dedupe(sorted []string) []string {
	out := sorted[:0]
	for i, l := range sorted {
		if i == 0 || l != sorted[i-1] {
			out = append(out, l)
		}
	}
	return out
}
