name: Go

on:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "docs/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yaml"
      - ".golangci.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.go"
      - "docs/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yaml"
      - ".golangci.yaml"

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.24", "1.25", "1.26"]
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
      - name: Execute golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.11.3
      - name: Run test
        run: make test
      - name: Run build
        run: make build
