name: Go

on:
  push:
    branches:
    - master
    paths:
    - "**/*.go"
    - "go.mod"
    - "go.sum"
  pull_request:
    branches:
    - master
    paths:
    - "**/*.go"
    - "go.mod"
    - "go.sum"

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13, 1.14, 1.15, 1.16]
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Execute golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: v1.41.1
    - name: Run test
      run: make test
    - name: Run build
      run: make build
