name: Label Sync

on:
  pull_request:
    types: [closed]

jobs:
  label-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # checkout v7
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c  # action-label-syncer v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
