// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: acor/v1/acor.proto

package acorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeywordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordRequest) Reset() {
	*x = KeywordRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordRequest) ProtoMessage() {}

func (x *KeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordRequest.ProtoReflect.Descriptor instead.
func (*KeywordRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{0}
}

func (x *KeywordRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type InputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{1}
}

func (x *InputRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{2}
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{3}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []string               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchesResponse) Reset() {
	*x = MatchesResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchesResponse) ProtoMessage() {}

func (x *MatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchesResponse.ProtoReflect.Descriptor instead.
func (*MatchesResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{4}
}

func (x *MatchesResponse) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

// Positions holds the start offsets of one matched keyword. Needed because
// proto3 maps cannot have a repeated value directly.
type Positions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []int64                `protobuf:"varint,1,rep,packed,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Positions) Reset() {
	*x = Positions{}
	mi := &file_acor_v1_acor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Positions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Positions) ProtoMessage() {}

func (x *Positions) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Positions.ProtoReflect.Descriptor instead.
func (*Positions) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{5}
}

func (x *Positions) GetPositions() []int64 {
	if x != nil {
		return x.Positions
	}
	return nil
}

type MatchIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       map[string]*Positions  `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchIndexesResponse) Reset() {
	*x = MatchIndexesResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchIndexesResponse) ProtoMessage() {}

func (x *MatchIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchIndexesResponse.ProtoReflect.Descriptor instead.
func (*MatchIndexesResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{6}
}

func (x *MatchIndexesResponse) GetMatches() map[string]*Positions {
	if x != nil {
		return x.Matches
	}
	return nil
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      int64                  `protobuf:"varint,1,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Nodes         int64                  `protobuf:"varint,2,opt,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{7}
}

func (x *InfoResponse) GetKeywords() int64 {
	if x != nil {
		return x.Keywords
	}
	return 0
}

func (x *InfoResponse) GetNodes() int64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VersionedStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActiveVersion      string                 `protobuf:"bytes,2,opt,name=active_version,json=activeVersion,proto3" json:"active_version,omitempty"`
	ServingVersion     string                 `protobuf:"bytes,3,opt,name=serving_version,json=servingVersion,proto3" json:"serving_version,omitempty"`
	Building           bool                   `protobuf:"varint,4,opt,name=building,proto3" json:"building,omitempty"`
	LastRefreshSuccess string                 `protobuf:"bytes,5,opt,name=last_refresh_success,json=lastRefreshSuccess,proto3" json:"last_refresh_success,omitempty"`
	LastRefreshFailure string                 `protobuf:"bytes,6,opt,name=last_refresh_failure,json=lastRefreshFailure,proto3" json:"last_refresh_failure,omitempty"`
	RefreshFailures    uint64                 `protobuf:"varint,7,opt,name=refresh_failures,json=refreshFailures,proto3" json:"refresh_failures,omitempty"`
	ActiveLeases       int64                  `protobuf:"varint,8,opt,name=active_leases,json=activeLeases,proto3" json:"active_leases,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VersionedStatusResponse) Reset() {
	*x = VersionedStatusResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedStatusResponse) ProtoMessage() {}

func (x *VersionedStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedStatusResponse.ProtoReflect.Descriptor instead.
func (*VersionedStatusResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{9}
}

func (x *VersionedStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VersionedStatusResponse) GetActiveVersion() string {
	if x != nil {
		return x.ActiveVersion
	}
	return ""
}

func (x *VersionedStatusResponse) GetServingVersion() string {
	if x != nil {
		return x.ServingVersion
	}
	return ""
}

func (x *VersionedStatusResponse) GetBuilding() bool {
	if x != nil {
		return x.Building
	}
	return false
}

func (x *VersionedStatusResponse) GetLastRefreshSuccess() string {
	if x != nil {
		return x.LastRefreshSuccess
	}
	return ""
}

func (x *VersionedStatusResponse) GetLastRefreshFailure() string {
	if x != nil {
		return x.LastRefreshFailure
	}
	return ""
}

func (x *VersionedStatusResponse) GetRefreshFailures() uint64 {
	if x != nil {
		return x.RefreshFailures
	}
	return 0
}

func (x *VersionedStatusResponse) GetActiveLeases() int64 {
	if x != nil {
		return x.ActiveLeases
	}
	return 0
}

type VersionedInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedInputRequest) Reset() {
	*x = VersionedInputRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedInputRequest) ProtoMessage() {}

func (x *VersionedInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedInputRequest.ProtoReflect.Descriptor instead.
func (*VersionedInputRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{10}
}

func (x *VersionedInputRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type VersionedScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	MaxInputBytes int64                  `protobuf:"varint,2,opt,name=max_input_bytes,json=maxInputBytes,proto3" json:"max_input_bytes,omitempty"`
	MaxMatches    int64                  `protobuf:"varint,3,opt,name=max_matches,json=maxMatches,proto3" json:"max_matches,omitempty"`
	MaxCandidates int64                  `protobuf:"varint,4,opt,name=max_candidates,json=maxCandidates,proto3" json:"max_candidates,omitempty"`
	Kind          int32                  `protobuf:"varint,5,opt,name=kind,proto3" json:"kind,omitempty"`
	WholeWord     bool                   `protobuf:"varint,6,opt,name=whole_word,json=wholeWord,proto3" json:"whole_word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedScanRequest) Reset() {
	*x = VersionedScanRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedScanRequest) ProtoMessage() {}

func (x *VersionedScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedScanRequest.ProtoReflect.Descriptor instead.
func (*VersionedScanRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{11}
}

func (x *VersionedScanRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *VersionedScanRequest) GetMaxInputBytes() int64 {
	if x != nil {
		return x.MaxInputBytes
	}
	return 0
}

func (x *VersionedScanRequest) GetMaxMatches() int64 {
	if x != nil {
		return x.MaxMatches
	}
	return 0
}

func (x *VersionedScanRequest) GetMaxCandidates() int64 {
	if x != nil {
		return x.MaxCandidates
	}
	return 0
}

func (x *VersionedScanRequest) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *VersionedScanRequest) GetWholeWord() bool {
	if x != nil {
		return x.WholeWord
	}
	return false
}

type VersionedRewriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Input          string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Replacement    string                 `protobuf:"bytes,2,opt,name=replacement,proto3" json:"replacement,omitempty"`
	Mask           string                 `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	MaxInputBytes  int64                  `protobuf:"varint,4,opt,name=max_input_bytes,json=maxInputBytes,proto3" json:"max_input_bytes,omitempty"`
	MaxMatches     int64                  `protobuf:"varint,5,opt,name=max_matches,json=maxMatches,proto3" json:"max_matches,omitempty"`
	MaxCandidates  int64                  `protobuf:"varint,6,opt,name=max_candidates,json=maxCandidates,proto3" json:"max_candidates,omitempty"`
	MaxOutputBytes int64                  `protobuf:"varint,7,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	WholeWord      bool                   `protobuf:"varint,8,opt,name=whole_word,json=wholeWord,proto3" json:"whole_word,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VersionedRewriteRequest) Reset() {
	*x = VersionedRewriteRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedRewriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedRewriteRequest) ProtoMessage() {}

func (x *VersionedRewriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedRewriteRequest.ProtoReflect.Descriptor instead.
func (*VersionedRewriteRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{12}
}

func (x *VersionedRewriteRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *VersionedRewriteRequest) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *VersionedRewriteRequest) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *VersionedRewriteRequest) GetMaxInputBytes() int64 {
	if x != nil {
		return x.MaxInputBytes
	}
	return 0
}

func (x *VersionedRewriteRequest) GetMaxMatches() int64 {
	if x != nil {
		return x.MaxMatches
	}
	return 0
}

func (x *VersionedRewriteRequest) GetMaxCandidates() int64 {
	if x != nil {
		return x.MaxCandidates
	}
	return 0
}

func (x *VersionedRewriteRequest) GetMaxOutputBytes() int64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *VersionedRewriteRequest) GetWholeWord() bool {
	if x != nil {
		return x.WholeWord
	}
	return false
}

type SourceMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Start         int64                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	ByteStart     int64                  `protobuf:"varint,5,opt,name=byte_start,json=byteStart,proto3" json:"byte_start,omitempty"`
	ByteEnd       int64                  `protobuf:"varint,6,opt,name=byte_end,json=byteEnd,proto3" json:"byte_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceMatch) Reset() {
	*x = SourceMatch{}
	mi := &file_acor_v1_acor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceMatch) ProtoMessage() {}

func (x *SourceMatch) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceMatch.ProtoReflect.Descriptor instead.
func (*SourceMatch) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{13}
}

func (x *SourceMatch) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SourceMatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SourceMatch) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SourceMatch) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *SourceMatch) GetByteStart() int64 {
	if x != nil {
		return x.ByteStart
	}
	return 0
}

func (x *SourceMatch) GetByteEnd() int64 {
	if x != nil {
		return x.ByteEnd
	}
	return 0
}

type VersionedScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*SourceMatch         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedScanResponse) Reset() {
	*x = VersionedScanResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedScanResponse) ProtoMessage() {}

func (x *VersionedScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedScanResponse.ProtoReflect.Descriptor instead.
func (*VersionedScanResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{14}
}

func (x *VersionedScanResponse) GetMatches() []*SourceMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *VersionedScanResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type VersionedRewriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Matches       []*SourceMatch         `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedRewriteResponse) Reset() {
	*x = VersionedRewriteResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedRewriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedRewriteResponse) ProtoMessage() {}

func (x *VersionedRewriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedRewriteResponse.ProtoReflect.Descriptor instead.
func (*VersionedRewriteResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{15}
}

func (x *VersionedRewriteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *VersionedRewriteResponse) GetMatches() []*SourceMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type VersionedWriteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExpectedVersion string                 `protobuf:"bytes,1,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Keyword         string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Keywords        []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VersionedWriteRequest) Reset() {
	*x = VersionedWriteRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedWriteRequest) ProtoMessage() {}

func (x *VersionedWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedWriteRequest.ProtoReflect.Descriptor instead.
func (*VersionedWriteRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{16}
}

func (x *VersionedWriteRequest) GetExpectedVersion() string {
	if x != nil {
		return x.ExpectedVersion
	}
	return ""
}

func (x *VersionedWriteRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *VersionedWriteRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type VersionedWriteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PreviousVersion string                 `protobuf:"bytes,1,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	OperationId     string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Added           int64                  `protobuf:"varint,4,opt,name=added,proto3" json:"added,omitempty"`
	Removed         int64                  `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
	Outcome         string                 `protobuf:"bytes,6,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VersionedWriteResponse) Reset() {
	*x = VersionedWriteResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedWriteResponse) ProtoMessage() {}

func (x *VersionedWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedWriteResponse.ProtoReflect.Descriptor instead.
func (*VersionedWriteResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{17}
}

func (x *VersionedWriteResponse) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *VersionedWriteResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionedWriteResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *VersionedWriteResponse) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *VersionedWriteResponse) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

func (x *VersionedWriteResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type VersionedWaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedWaitRequest) Reset() {
	*x = VersionedWaitRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedWaitRequest) ProtoMessage() {}

func (x *VersionedWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedWaitRequest.ProtoReflect.Descriptor instead.
func (*VersionedWaitRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{18}
}

func (x *VersionedWaitRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResolveOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveOperationRequest) Reset() {
	*x = ResolveOperationRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveOperationRequest) ProtoMessage() {}

func (x *ResolveOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveOperationRequest.ProtoReflect.Descriptor instead.
func (*ResolveOperationRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

var File_acor_v1_acor_proto protoreflect.FileDescriptor

const file_acor_v1_acor_proto_rawDesc = "" +
	"\n" +
	"\x12acor/v1/acor.proto\x12\x0eacor.server.v1\"*\n" +
	"\x0eKeywordRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"$\n" +
	"\fInputRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\x0e\n" +
	"\fEmptyRequest\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"+\n" +
	"\x0fMatchesResponse\x12\x18\n" +
	"\amatches\x18\x01 \x03(\tR\amatches\")\n" +
	"\tPositions\x12\x1c\n" +
	"\tpositions\x18\x01 \x03(\x03R\tpositions\"\xba\x01\n" +
	"\x14MatchIndexesResponse\x12K\n" +
	"\amatches\x18\x01 \x03(\v21.acor.server.v1.MatchIndexesResponse.MatchesEntryR\amatches\x1aU\n" +
	"\fMatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.acor.server.v1.PositionsR\x05value:\x028\x01\"@\n" +
	"\fInfoResponse\x12\x1a\n" +
	"\bkeywords\x18\x01 \x01(\x03R\bkeywords\x12\x14\n" +
	"\x05nodes\x18\x02 \x01(\x03R\x05nodes\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xd1\x02\n" +
	"\x17VersionedStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0eactive_version\x18\x02 \x01(\tR\ractiveVersion\x12'\n" +
	"\x0fserving_version\x18\x03 \x01(\tR\x0eservingVersion\x12\x1a\n" +
	"\bbuilding\x18\x04 \x01(\bR\bbuilding\x120\n" +
	"\x14last_refresh_success\x18\x05 \x01(\tR\x12lastRefreshSuccess\x120\n" +
	"\x14last_refresh_failure\x18\x06 \x01(\tR\x12lastRefreshFailure\x12)\n" +
	"\x10refresh_failures\x18\a \x01(\x04R\x0frefreshFailures\x12#\n" +
	"\ractive_leases\x18\b \x01(\x03R\factiveLeases\"-\n" +
	"\x15VersionedInputRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\xcf\x01\n" +
	"\x14VersionedScanRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12&\n" +
	"\x0fmax_input_bytes\x18\x02 \x01(\x03R\rmaxInputBytes\x12\x1f\n" +
	"\vmax_matches\x18\x03 \x01(\x03R\n" +
	"maxMatches\x12%\n" +
	"\x0emax_candidates\x18\x04 \x01(\x03R\rmaxCandidates\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\x05R\x04kind\x12\x1d\n" +
	"\n" +
	"whole_word\x18\x06 \x01(\bR\twholeWord\"\x9e\x02\n" +
	"\x17VersionedRewriteRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12 \n" +
	"\vreplacement\x18\x02 \x01(\tR\vreplacement\x12\x12\n" +
	"\x04mask\x18\x03 \x01(\tR\x04mask\x12&\n" +
	"\x0fmax_input_bytes\x18\x04 \x01(\x03R\rmaxInputBytes\x12\x1f\n" +
	"\vmax_matches\x18\x05 \x01(\x03R\n" +
	"maxMatches\x12%\n" +
	"\x0emax_candidates\x18\x06 \x01(\x03R\rmaxCandidates\x12(\n" +
	"\x10max_output_bytes\x18\a \x01(\x03R\x0emaxOutputBytes\x12\x1d\n" +
	"\n" +
	"whole_word\x18\b \x01(\bR\twholeWord\"\x9d\x01\n" +
	"\vSourceMatch\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x03R\x03end\x12\x1d\n" +
	"\n" +
	"byte_start\x18\x05 \x01(\x03R\tbyteStart\x12\x19\n" +
	"\bbyte_end\x18\x06 \x01(\x03R\abyteEnd\"l\n" +
	"\x15VersionedScanResponse\x125\n" +
	"\amatches\x18\x01 \x03(\v2\x1b.acor.server.v1.SourceMatchR\amatches\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"e\n" +
	"\x18VersionedRewriteResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x125\n" +
	"\amatches\x18\x02 \x03(\v2\x1b.acor.server.v1.SourceMatchR\amatches\"x\n" +
	"\x15VersionedWriteRequest\x12)\n" +
	"\x10expected_version\x18\x01 \x01(\tR\x0fexpectedVersion\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\"\xca\x01\n" +
	"\x16VersionedWriteResponse\x12)\n" +
	"\x10previous_version\x18\x01 \x01(\tR\x0fpreviousVersion\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12\x14\n" +
	"\x05added\x18\x04 \x01(\x03R\x05added\x12\x18\n" +
	"\aremoved\x18\x05 \x01(\x03R\aremoved\x12\x18\n" +
	"\aoutcome\x18\x06 \x01(\tR\aoutcome\"0\n" +
	"\x14VersionedWaitRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"<\n" +
	"\x17ResolveOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId2\xd6\r\n" +
	"\x04Acor\x12D\n" +
	"\x03Add\x12\x1e.acor.server.v1.KeywordRequest\x1a\x1d.acor.server.v1.CountResponse\x12G\n" +
	"\x06Remove\x12\x1e.acor.server.v1.KeywordRequest\x1a\x1d.acor.server.v1.CountResponse\x12E\n" +
	"\x04Find\x12\x1c.acor.server.v1.InputRequest\x1a\x1f.acor.server.v1.MatchesResponse\x12O\n" +
	"\tFindIndex\x12\x1c.acor.server.v1.InputRequest\x1a$.acor.server.v1.MatchIndexesResponse\x12H\n" +
	"\aSuggest\x12\x1c.acor.server.v1.InputRequest\x1a\x1f.acor.server.v1.MatchesResponse\x12R\n" +
	"\fSuggestIndex\x12\x1c.acor.server.v1.InputRequest\x1a$.acor.server.v1.MatchIndexesResponse\x12B\n" +
	"\x04Info\x12\x1c.acor.server.v1.EmptyRequest\x1a\x1c.acor.server.v1.InfoResponse\x12E\n" +
	"\x05Flush\x12\x1c.acor.server.v1.EmptyRequest\x1a\x1e.acor.server.v1.StatusResponse\x12O\n" +
	"\x06Status\x12\x1c.acor.server.v1.EmptyRequest\x1a'.acor.server.v1.VersionedStatusResponse\x12W\n" +
	"\rVersionedFind\x12%.acor.server.v1.VersionedInputRequest\x1a\x1f.acor.server.v1.MatchesResponse\x12\\\n" +
	"\rVersionedScan\x12$.acor.server.v1.VersionedScanRequest\x1a%.acor.server.v1.VersionedScanResponse\x12b\n" +
	"\rVersionedMask\x12'.acor.server.v1.VersionedRewriteRequest\x1a(.acor.server.v1.VersionedRewriteResponse\x12i\n" +
	"\x14VersionedReplaceText\x12'.acor.server.v1.VersionedRewriteRequest\x1a(.acor.server.v1.VersionedRewriteResponse\x12a\n" +
	"\x10VersionedReplace\x12%.acor.server.v1.VersionedWriteRequest\x1a&.acor.server.v1.VersionedWriteResponse\x12]\n" +
	"\fVersionedAdd\x12%.acor.server.v1.VersionedWriteRequest\x1a&.acor.server.v1.VersionedWriteResponse\x12`\n" +
	"\x0fVersionedRemove\x12%.acor.server.v1.VersionedWriteRequest\x1a&.acor.server.v1.VersionedWriteResponse\x12a\n" +
	"\x10VersionedAddMany\x12%.acor.server.v1.VersionedWriteRequest\x1a&.acor.server.v1.VersionedWriteResponse\x12d\n" +
	"\x13VersionedRemoveMany\x12%.acor.server.v1.VersionedWriteRequest\x1a&.acor.server.v1.VersionedWriteResponse\x12U\n" +
	"\rVersionedWait\x12$.acor.server.v1.VersionedWaitRequest\x1a\x1e.acor.server.v1.StatusResponse\x12c\n" +
	"\x10ResolveOperation\x12'.acor.server.v1.ResolveOperationRequest\x1a&.acor.server.v1.VersionedWriteResponseB7Z5github.com/skyoo2003/acor/server/proto/acor/v1;acorv1b\x06proto3"

var (
	file_acor_v1_acor_proto_rawDescOnce sync.Once
	file_acor_v1_acor_proto_rawDescData []byte
)

func file_acor_v1_acor_proto_rawDescGZIP() []byte {
	file_acor_v1_acor_proto_rawDescOnce.Do(func() {
		file_acor_v1_acor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acor_v1_acor_proto_rawDesc), len(file_acor_v1_acor_proto_rawDesc)))
	})
	return file_acor_v1_acor_proto_rawDescData
}

var file_acor_v1_acor_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_acor_v1_acor_proto_goTypes = []any{
	(*KeywordRequest)(nil),           // 0: acor.server.v1.KeywordRequest
	(*InputRequest)(nil),             // 1: acor.server.v1.InputRequest
	(*EmptyRequest)(nil),             // 2: acor.server.v1.EmptyRequest
	(*CountResponse)(nil),            // 3: acor.server.v1.CountResponse
	(*MatchesResponse)(nil),          // 4: acor.server.v1.MatchesResponse
	(*Positions)(nil),                // 5: acor.server.v1.Positions
	(*MatchIndexesResponse)(nil),     // 6: acor.server.v1.MatchIndexesResponse
	(*InfoResponse)(nil),             // 7: acor.server.v1.InfoResponse
	(*StatusResponse)(nil),           // 8: acor.server.v1.StatusResponse
	(*VersionedStatusResponse)(nil),  // 9: acor.server.v1.VersionedStatusResponse
	(*VersionedInputRequest)(nil),    // 10: acor.server.v1.VersionedInputRequest
	(*VersionedScanRequest)(nil),     // 11: acor.server.v1.VersionedScanRequest
	(*VersionedRewriteRequest)(nil),  // 12: acor.server.v1.VersionedRewriteRequest
	(*SourceMatch)(nil),              // 13: acor.server.v1.SourceMatch
	(*VersionedScanResponse)(nil),    // 14: acor.server.v1.VersionedScanResponse
	(*VersionedRewriteResponse)(nil), // 15: acor.server.v1.VersionedRewriteResponse
	(*VersionedWriteRequest)(nil),    // 16: acor.server.v1.VersionedWriteRequest
	(*VersionedWriteResponse)(nil),   // 17: acor.server.v1.VersionedWriteResponse
	(*VersionedWaitRequest)(nil),     // 18: acor.server.v1.VersionedWaitRequest
	(*ResolveOperationRequest)(nil),  // 19: acor.server.v1.ResolveOperationRequest
	nil,                              // 20: acor.server.v1.MatchIndexesResponse.MatchesEntry
}
var file_acor_v1_acor_proto_depIdxs = []int32{
	20, // 0: acor.server.v1.MatchIndexesResponse.matches:type_name -> acor.server.v1.MatchIndexesResponse.MatchesEntry
	13, // 1: acor.server.v1.VersionedScanResponse.matches:type_name -> acor.server.v1.SourceMatch
	13, // 2: acor.server.v1.VersionedRewriteResponse.matches:type_name -> acor.server.v1.SourceMatch
	5,  // 3: acor.server.v1.MatchIndexesResponse.MatchesEntry.value:type_name -> acor.server.v1.Positions
	0,  // 4: acor.server.v1.Acor.Add:input_type -> acor.server.v1.KeywordRequest
	0,  // 5: acor.server.v1.Acor.Remove:input_type -> acor.server.v1.KeywordRequest
	1,  // 6: acor.server.v1.Acor.Find:input_type -> acor.server.v1.InputRequest
	1,  // 7: acor.server.v1.Acor.FindIndex:input_type -> acor.server.v1.InputRequest
	1,  // 8: acor.server.v1.Acor.Suggest:input_type -> acor.server.v1.InputRequest
	1,  // 9: acor.server.v1.Acor.SuggestIndex:input_type -> acor.server.v1.InputRequest
	2,  // 10: acor.server.v1.Acor.Info:input_type -> acor.server.v1.EmptyRequest
	2,  // 11: acor.server.v1.Acor.Flush:input_type -> acor.server.v1.EmptyRequest
	2,  // 12: acor.server.v1.Acor.Status:input_type -> acor.server.v1.EmptyRequest
	10, // 13: acor.server.v1.Acor.VersionedFind:input_type -> acor.server.v1.VersionedInputRequest
	11, // 14: acor.server.v1.Acor.VersionedScan:input_type -> acor.server.v1.VersionedScanRequest
	12, // 15: acor.server.v1.Acor.VersionedMask:input_type -> acor.server.v1.VersionedRewriteRequest
	12, // 16: acor.server.v1.Acor.VersionedReplaceText:input_type -> acor.server.v1.VersionedRewriteRequest
	16, // 17: acor.server.v1.Acor.VersionedReplace:input_type -> acor.server.v1.VersionedWriteRequest
	16, // 18: acor.server.v1.Acor.VersionedAdd:input_type -> acor.server.v1.VersionedWriteRequest
	16, // 19: acor.server.v1.Acor.VersionedRemove:input_type -> acor.server.v1.VersionedWriteRequest
	16, // 20: acor.server.v1.Acor.VersionedAddMany:input_type -> acor.server.v1.VersionedWriteRequest
	16, // 21: acor.server.v1.Acor.VersionedRemoveMany:input_type -> acor.server.v1.VersionedWriteRequest
	18, // 22: acor.server.v1.Acor.VersionedWait:input_type -> acor.server.v1.VersionedWaitRequest
	19, // 23: acor.server.v1.Acor.ResolveOperation:input_type -> acor.server.v1.ResolveOperationRequest
	3,  // 24: acor.server.v1.Acor.Add:output_type -> acor.server.v1.CountResponse
	3,  // 25: acor.server.v1.Acor.Remove:output_type -> acor.server.v1.CountResponse
	4,  // 26: acor.server.v1.Acor.Find:output_type -> acor.server.v1.MatchesResponse
	6,  // 27: acor.server.v1.Acor.FindIndex:output_type -> acor.server.v1.MatchIndexesResponse
	4,  // 28: acor.server.v1.Acor.Suggest:output_type -> acor.server.v1.MatchesResponse
	6,  // 29: acor.server.v1.Acor.SuggestIndex:output_type -> acor.server.v1.MatchIndexesResponse
	7,  // 30: acor.server.v1.Acor.Info:output_type -> acor.server.v1.InfoResponse
	8,  // 31: acor.server.v1.Acor.Flush:output_type -> acor.server.v1.StatusResponse
	9,  // 32: acor.server.v1.Acor.Status:output_type -> acor.server.v1.VersionedStatusResponse
	4,  // 33: acor.server.v1.Acor.VersionedFind:output_type -> acor.server.v1.MatchesResponse
	14, // 34: acor.server.v1.Acor.VersionedScan:output_type -> acor.server.v1.VersionedScanResponse
	15, // 35: acor.server.v1.Acor.VersionedMask:output_type -> acor.server.v1.VersionedRewriteResponse
	15, // 36: acor.server.v1.Acor.VersionedReplaceText:output_type -> acor.server.v1.VersionedRewriteResponse
	17, // 37: acor.server.v1.Acor.VersionedReplace:output_type -> acor.server.v1.VersionedWriteResponse
	17, // 38: acor.server.v1.Acor.VersionedAdd:output_type -> acor.server.v1.VersionedWriteResponse
	17, // 39: acor.server.v1.Acor.VersionedRemove:output_type -> acor.server.v1.VersionedWriteResponse
	17, // 40: acor.server.v1.Acor.VersionedAddMany:output_type -> acor.server.v1.VersionedWriteResponse
	17, // 41: acor.server.v1.Acor.VersionedRemoveMany:output_type -> acor.server.v1.VersionedWriteResponse
	8,  // 42: acor.server.v1.Acor.VersionedWait:output_type -> acor.server.v1.StatusResponse
	17, // 43: acor.server.v1.Acor.ResolveOperation:output_type -> acor.server.v1.VersionedWriteResponse
	24, // [24:44] is the sub-list for method output_type
	4,  // [4:24] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_acor_v1_acor_proto_init() }
func file_acor_v1_acor_proto_init() {
	if File_acor_v1_acor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acor_v1_acor_proto_rawDesc), len(file_acor_v1_acor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acor_v1_acor_proto_goTypes,
		DependencyIndexes: file_acor_v1_acor_proto_depIdxs,
		MessageInfos:      file_acor_v1_acor_proto_msgTypes,
	}.Build()
	File_acor_v1_acor_proto = out.File
	file_acor_v1_acor_proto_goTypes = nil
	file_acor_v1_acor_proto_depIdxs = nil
}
