// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: acor/v1/acor.proto

package acorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeywordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordRequest) Reset() {
	*x = KeywordRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordRequest) ProtoMessage() {}

func (x *KeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordRequest.ProtoReflect.Descriptor instead.
func (*KeywordRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{0}
}

func (x *KeywordRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type InputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{1}
}

func (x *InputRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_acor_v1_acor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{2}
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{3}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MatchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []string               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchesResponse) Reset() {
	*x = MatchesResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchesResponse) ProtoMessage() {}

func (x *MatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchesResponse.ProtoReflect.Descriptor instead.
func (*MatchesResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{4}
}

func (x *MatchesResponse) GetMatches() []string {
	if x != nil {
		return x.Matches
	}
	return nil
}

// Positions holds the start offsets of one matched keyword. Needed because
// proto3 maps cannot have a repeated value directly.
type Positions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []int64                `protobuf:"varint,1,rep,packed,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Positions) Reset() {
	*x = Positions{}
	mi := &file_acor_v1_acor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Positions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Positions) ProtoMessage() {}

func (x *Positions) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Positions.ProtoReflect.Descriptor instead.
func (*Positions) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{5}
}

func (x *Positions) GetPositions() []int64 {
	if x != nil {
		return x.Positions
	}
	return nil
}

type MatchIndexesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       map[string]*Positions  `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchIndexesResponse) Reset() {
	*x = MatchIndexesResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchIndexesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchIndexesResponse) ProtoMessage() {}

func (x *MatchIndexesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchIndexesResponse.ProtoReflect.Descriptor instead.
func (*MatchIndexesResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{6}
}

func (x *MatchIndexesResponse) GetMatches() map[string]*Positions {
	if x != nil {
		return x.Matches
	}
	return nil
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      int64                  `protobuf:"varint,1,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Nodes         int64                  `protobuf:"varint,2,opt,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{7}
}

func (x *InfoResponse) GetKeywords() int64 {
	if x != nil {
		return x.Keywords
	}
	return 0
}

func (x *InfoResponse) GetNodes() int64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_acor_v1_acor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_acor_v1_acor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_acor_v1_acor_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_acor_v1_acor_proto protoreflect.FileDescriptor

const file_acor_v1_acor_proto_rawDesc = "" +
	"\n" +
	"\x12acor/v1/acor.proto\x12\x0eacor.server.v1\"*\n" +
	"\x0eKeywordRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"$\n" +
	"\fInputRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"\x0e\n" +
	"\fEmptyRequest\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"+\n" +
	"\x0fMatchesResponse\x12\x18\n" +
	"\amatches\x18\x01 \x03(\tR\amatches\")\n" +
	"\tPositions\x12\x1c\n" +
	"\tpositions\x18\x01 \x03(\x03R\tpositions\"\xba\x01\n" +
	"\x14MatchIndexesResponse\x12K\n" +
	"\amatches\x18\x01 \x03(\v21.acor.server.v1.MatchIndexesResponse.MatchesEntryR\amatches\x1aU\n" +
	"\fMatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.acor.server.v1.PositionsR\x05value:\x028\x01\"@\n" +
	"\fInfoResponse\x12\x1a\n" +
	"\bkeywords\x18\x01 \x01(\x03R\bkeywords\x12\x14\n" +
	"\x05nodes\x18\x02 \x01(\x03R\x05nodes\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xd6\x04\n" +
	"\x04Acor\x12D\n" +
	"\x03Add\x12\x1e.acor.server.v1.KeywordRequest\x1a\x1d.acor.server.v1.CountResponse\x12G\n" +
	"\x06Remove\x12\x1e.acor.server.v1.KeywordRequest\x1a\x1d.acor.server.v1.CountResponse\x12E\n" +
	"\x04Find\x12\x1c.acor.server.v1.InputRequest\x1a\x1f.acor.server.v1.MatchesResponse\x12O\n" +
	"\tFindIndex\x12\x1c.acor.server.v1.InputRequest\x1a$.acor.server.v1.MatchIndexesResponse\x12H\n" +
	"\aSuggest\x12\x1c.acor.server.v1.InputRequest\x1a\x1f.acor.server.v1.MatchesResponse\x12R\n" +
	"\fSuggestIndex\x12\x1c.acor.server.v1.InputRequest\x1a$.acor.server.v1.MatchIndexesResponse\x12B\n" +
	"\x04Info\x12\x1c.acor.server.v1.EmptyRequest\x1a\x1c.acor.server.v1.InfoResponse\x12E\n" +
	"\x05Flush\x12\x1c.acor.server.v1.EmptyRequest\x1a\x1e.acor.server.v1.StatusResponseB7Z5github.com/skyoo2003/acor/server/proto/acor/v1;acorv1b\x06proto3"

var (
	file_acor_v1_acor_proto_rawDescOnce sync.Once
	file_acor_v1_acor_proto_rawDescData []byte
)

func file_acor_v1_acor_proto_rawDescGZIP() []byte {
	file_acor_v1_acor_proto_rawDescOnce.Do(func() {
		file_acor_v1_acor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acor_v1_acor_proto_rawDesc), len(file_acor_v1_acor_proto_rawDesc)))
	})
	return file_acor_v1_acor_proto_rawDescData
}

var file_acor_v1_acor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_acor_v1_acor_proto_goTypes = []any{
	(*KeywordRequest)(nil),       // 0: acor.server.v1.KeywordRequest
	(*InputRequest)(nil),         // 1: acor.server.v1.InputRequest
	(*EmptyRequest)(nil),         // 2: acor.server.v1.EmptyRequest
	(*CountResponse)(nil),        // 3: acor.server.v1.CountResponse
	(*MatchesResponse)(nil),      // 4: acor.server.v1.MatchesResponse
	(*Positions)(nil),            // 5: acor.server.v1.Positions
	(*MatchIndexesResponse)(nil), // 6: acor.server.v1.MatchIndexesResponse
	(*InfoResponse)(nil),         // 7: acor.server.v1.InfoResponse
	(*StatusResponse)(nil),       // 8: acor.server.v1.StatusResponse
	nil,                          // 9: acor.server.v1.MatchIndexesResponse.MatchesEntry
}
var file_acor_v1_acor_proto_depIdxs = []int32{
	9,  // 0: acor.server.v1.MatchIndexesResponse.matches:type_name -> acor.server.v1.MatchIndexesResponse.MatchesEntry
	5,  // 1: acor.server.v1.MatchIndexesResponse.MatchesEntry.value:type_name -> acor.server.v1.Positions
	0,  // 2: acor.server.v1.Acor.Add:input_type -> acor.server.v1.KeywordRequest
	0,  // 3: acor.server.v1.Acor.Remove:input_type -> acor.server.v1.KeywordRequest
	1,  // 4: acor.server.v1.Acor.Find:input_type -> acor.server.v1.InputRequest
	1,  // 5: acor.server.v1.Acor.FindIndex:input_type -> acor.server.v1.InputRequest
	1,  // 6: acor.server.v1.Acor.Suggest:input_type -> acor.server.v1.InputRequest
	1,  // 7: acor.server.v1.Acor.SuggestIndex:input_type -> acor.server.v1.InputRequest
	2,  // 8: acor.server.v1.Acor.Info:input_type -> acor.server.v1.EmptyRequest
	2,  // 9: acor.server.v1.Acor.Flush:input_type -> acor.server.v1.EmptyRequest
	3,  // 10: acor.server.v1.Acor.Add:output_type -> acor.server.v1.CountResponse
	3,  // 11: acor.server.v1.Acor.Remove:output_type -> acor.server.v1.CountResponse
	4,  // 12: acor.server.v1.Acor.Find:output_type -> acor.server.v1.MatchesResponse
	6,  // 13: acor.server.v1.Acor.FindIndex:output_type -> acor.server.v1.MatchIndexesResponse
	4,  // 14: acor.server.v1.Acor.Suggest:output_type -> acor.server.v1.MatchesResponse
	6,  // 15: acor.server.v1.Acor.SuggestIndex:output_type -> acor.server.v1.MatchIndexesResponse
	7,  // 16: acor.server.v1.Acor.Info:output_type -> acor.server.v1.InfoResponse
	8,  // 17: acor.server.v1.Acor.Flush:output_type -> acor.server.v1.StatusResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_acor_v1_acor_proto_init() }
func file_acor_v1_acor_proto_init() {
	if File_acor_v1_acor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acor_v1_acor_proto_rawDesc), len(file_acor_v1_acor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acor_v1_acor_proto_goTypes,
		DependencyIndexes: file_acor_v1_acor_proto_depIdxs,
		MessageInfos:      file_acor_v1_acor_proto_msgTypes,
	}.Build()
	File_acor_v1_acor_proto = out.File
	file_acor_v1_acor_proto_goTypes = nil
	file_acor_v1_acor_proto_depIdxs = nil
}
