// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: acor/v1/acor.proto

package acorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Acor_Add_FullMethodName          = "/acor.server.v1.Acor/Add"
	Acor_Remove_FullMethodName       = "/acor.server.v1.Acor/Remove"
	Acor_Find_FullMethodName         = "/acor.server.v1.Acor/Find"
	Acor_FindIndex_FullMethodName    = "/acor.server.v1.Acor/FindIndex"
	Acor_Suggest_FullMethodName      = "/acor.server.v1.Acor/Suggest"
	Acor_SuggestIndex_FullMethodName = "/acor.server.v1.Acor/SuggestIndex"
	Acor_Info_FullMethodName         = "/acor.server.v1.Acor/Info"
	Acor_Flush_FullMethodName        = "/acor.server.v1.Acor/Flush"
)

// AcorClient is the client API for Acor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Acor is the gRPC surface for an Aho-Corasick keyword collection. It mirrors
// the HTTP/JSON adapter one-to-one.
type AcorClient interface {
	Add(ctx context.Context, in *KeywordRequest, opts ...grpc.CallOption) (*CountResponse, error)
	Remove(ctx context.Context, in *KeywordRequest, opts ...grpc.CallOption) (*CountResponse, error)
	Find(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchesResponse, error)
	FindIndex(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchIndexesResponse, error)
	Suggest(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchesResponse, error)
	SuggestIndex(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchIndexesResponse, error)
	Info(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Flush(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type acorClient struct {
	cc grpc.ClientConnInterface
}

func NewAcorClient(cc grpc.ClientConnInterface) AcorClient {
	return &acorClient{cc}
}

func (c *acorClient) Add(ctx context.Context, in *KeywordRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, Acor_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acorClient) Remove(ctx context.Context, in *KeywordRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, Acor_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acorClient) Find(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchesResponse)
	err := c.cc.Invoke(ctx, Acor_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acorClient) FindIndex(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchIndexesResponse)
	err := c.cc.Invoke(ctx, Acor_FindIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acorClient) Suggest(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchesResponse)
	err := c.cc.Invoke(ctx, Acor_Suggest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acorClient) SuggestIndex(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*MatchIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchIndexesResponse)
	err := c.cc.Invoke(ctx, Acor_SuggestIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acorClient) Info(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, Acor_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *acorClient) Flush(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Acor_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcorServer is the server API for Acor service.
// All implementations must embed UnimplementedAcorServer
// for forward compatibility.
//
// Acor is the gRPC surface for an Aho-Corasick keyword collection. It mirrors
// the HTTP/JSON adapter one-to-one.
type AcorServer interface {
	Add(context.Context, *KeywordRequest) (*CountResponse, error)
	Remove(context.Context, *KeywordRequest) (*CountResponse, error)
	Find(context.Context, *InputRequest) (*MatchesResponse, error)
	FindIndex(context.Context, *InputRequest) (*MatchIndexesResponse, error)
	Suggest(context.Context, *InputRequest) (*MatchesResponse, error)
	SuggestIndex(context.Context, *InputRequest) (*MatchIndexesResponse, error)
	Info(context.Context, *EmptyRequest) (*InfoResponse, error)
	Flush(context.Context, *EmptyRequest) (*StatusResponse, error)
	mustEmbedUnimplementedAcorServer()
}

// UnimplementedAcorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcorServer struct{}

func (UnimplementedAcorServer) Add(context.Context, *KeywordRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedAcorServer) Remove(context.Context, *KeywordRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedAcorServer) Find(context.Context, *InputRequest) (*MatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedAcorServer) FindIndex(context.Context, *InputRequest) (*MatchIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindIndex not implemented")
}
func (UnimplementedAcorServer) Suggest(context.Context, *InputRequest) (*MatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Suggest not implemented")
}
func (UnimplementedAcorServer) SuggestIndex(context.Context, *InputRequest) (*MatchIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestIndex not implemented")
}
func (UnimplementedAcorServer) Info(context.Context, *EmptyRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAcorServer) Flush(context.Context, *EmptyRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedAcorServer) mustEmbedUnimplementedAcorServer() {}
func (UnimplementedAcorServer) testEmbeddedByValue()              {}

// UnsafeAcorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcorServer will
// result in compilation errors.
type UnsafeAcorServer interface {
	mustEmbedUnimplementedAcorServer()
}

func RegisterAcorServer(s grpc.ServiceRegistrar, srv AcorServer) {
	// If the following call panics, it indicates UnimplementedAcorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Acor_ServiceDesc, srv)
}

func _Acor_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeywordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).Add(ctx, req.(*KeywordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acor_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeywordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).Remove(ctx, req.(*KeywordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acor_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).Find(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acor_FindIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).FindIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_FindIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).FindIndex(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acor_Suggest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).Suggest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_Suggest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).Suggest(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acor_SuggestIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).SuggestIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_SuggestIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).SuggestIndex(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acor_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).Info(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Acor_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcorServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acor_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcorServer).Flush(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Acor_ServiceDesc is the grpc.ServiceDesc for Acor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Acor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acor.server.v1.Acor",
	HandlerType: (*AcorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Acor_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Acor_Remove_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _Acor_Find_Handler,
		},
		{
			MethodName: "FindIndex",
			Handler:    _Acor_FindIndex_Handler,
		},
		{
			MethodName: "Suggest",
			Handler:    _Acor_Suggest_Handler,
		},
		{
			MethodName: "SuggestIndex",
			Handler:    _Acor_SuggestIndex_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Acor_Info_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _Acor_Flush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "acor/v1/acor.proto",
}
